sonar.projectKey=Mathiousse_pub-sub-app
sonar.organization=mathiousse

# Only include C# files
sonar.sources=RabbitMqProductAPI
sonar.exclusions=**/*.js,**/*.html,**/*.css
sonar.language=cs
sonar.sourceEncoding=UTF-8

# Test coverage configuration
sonar.cs.vstest.reportsPaths=RabbitMqProductAPI/TestResults/*.trx
sonar.cs.opencover.reportsPaths=RabbitMqProductAPI/TestResults/coverage.opencover.xml

# Project structure
sonar.projectBaseDir=.
sonar.working.directory=.scannerwork
