sonar.projectKey=Mathiousse_pub-sub-app
sonar.organization=mathiousse

sonar.sources=.
sonar.sourceEncoding=UTF-8

# C# specific settings
sonar.cs.vstest.reportsPaths=**/TestResults/*.trx
sonar.cs.opencover.reportsPaths=**/TestResults/coverage.opencover.xml
sonar.cs.msbuild.basePath=RabbitMqProductAPI
sonar.projectBaseDir=RabbitMqProductAPI
