name: API Tests and Analysis

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      PROJECT_FOLDER: "RabbitMqProductAPI"
      PROJECT_NAME: "RabbitMqProductAPI"
      DOTNET_VERSION: "6.0.419"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=mathiousse
            -Dsonar.projectKey=Mathiousse_pub-sub-app
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
            -Dsonar.branch.name=${{ github.ref_name }}
            # Removed the following line to prevent conflict with main branch
            # -Dsonar.branch.target=develop
            -Dsonar.cs.vstest.reportsPaths=**/*.trx
            -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml

      - name: Run Tests
        working-directory: ${{ env.PROJECT_FOLDER }}
        run: >
          dotnet test 
          --logger "trx;LogFileName=test-results.trx" 
          --results-directory "./TestResults"
          /p:CollectCoverage=true 
          /p:CoverletOutputFormat=opencover

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ${{ env.PROJECT_FOLDER }}/TestResults/*.trx
