name: API Tests and Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      PROJECT_FOLDER: "RabbitMqProductAPI"
      PROJECT_NAME: "RabbitMqProductAPI"
      DOTNET_VERSION: "9.x"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=${{ env.PROJECT_NAME }}
            -Dsonar.sources=.
            -Dsonar.cs.vstest.reportsPaths=**/TestResults/*.trx
            -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml

      - name: Run Tests
        working-directory: ${{ env.PROJECT_FOLDER }}
        run: >
          dotnet test --logger "trx;LogFileName=test-results.trx"
          /p:CollectCoverage=true
          /p:CoverletOutputFormat=opencover

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ${{ env.PROJECT_FOLDER }}/**/TestResults/*.trx
