name: Build and deploy API
on:      
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          
      - name: dotnet build
        run: dotnet build
        
      - name: dotnet publish
        run: |
          dotnet publish ./RabbitMqProductAPI/RabbitMqProductAPI.csproj -c Release -o ./publish/api
          dotnet publish ./RabbitMQProduct.ConsoleApplication/RabbitMQProduct.ConsoleApplication.csproj -c Release -o ./publish/console
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: |
            ./publish/api
            ./publish/console
          retention-days: 5

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: pub-sub
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish/api

